In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_json('leetcode-solution.jsonl', lines=True)

In [3]:
df

,id,slug,title,difficulty,content,answer
0,1,two-sum,Two Sum,Easy,Given an array of integers `nums` and an integ...,{'c++': '```cpp #include <vector> #include <un...
1,2,add-two-numbers,Add Two Numbers,Medium,You are given two **non-empty** linked lists r...,{'c++': '```cpp struct ListNode { int val;...
2,3,longest-substring-without-repeating-characters,Longest Substring Without Repeating Characters,Medium,"Given a string `s`, find the length of the **l...",{'c++': '```cpp #include <string> #include <un...
3,4,median-of-two-sorted-arrays,Median of Two Sorted Arrays,Hard,Given two sorted arrays `nums1` and `nums2` of...,{'c++': '```cpp double findMedianSortedArrays(...
4,5,longest-palindromic-substring,Longest Palindromic Substring,Medium,"Given a string `s`, return _the longest_ _pali...",{'c++': '```cpp #include <string> std::string...
...,...,...,...,...,...,...
2355,2608,shortest-cycle-in-a-graph,Shortest Cycle in a Graph,Hard,There is a **bi-directional** graph with `n` v...,{'c++': '```cpp #include <vector> #include <qu...
2356,2609,find-the-longest-balanced-substring-of-a-binar...,Find the Longest Balanced Substring of a Binar...,Easy,You are given a binary string `s` consisting o...,{'c++': '```cpp int longestBalancedSubstring(s...
2357,2610,convert-an-array-into-a-2d-array-with-conditions,Convert an Array Into a 2D Array With Conditions,Medium,You are given an integer array `nums`. You nee...,{'c++': '```cpp #include <vector> #include <un...
2358,2611,mice-and-cheese,Mice and Cheese,Medium,There are two mice and `n` different types of ...,{'c++': '```cpp #include <vector> #include <al...
2359,2612,minimum-reverse-operations,Minimum Reverse Operations,Hard,You are given an integer `n` and an integer `p...,{'c++': '```cpp #include <vector> #include <se...

In [4]:
# Set randomly the difficulty, easy in range (1000- 3000), medium in range (3000 - 6000), hard in range (6000 - 10000)
def set_difficulty(row):
    if row['difficulty'] == 'Easy':
        return np.random.randint(1000, 3000)
    elif row['difficulty'] == 'Medium':
        return np.random.randint(3000, 6000)
    else:
        return np.random.randint(6000, 10000)
df['difficulty'] = df.apply(set_difficulty, axis=1)

In [5]:
df

,id,slug,title,difficulty,content,answer
0,1,two-sum,Two Sum,2812,Given an array of integers `nums` and an integ...,{'c++': '```cpp #include <vector> #include <un...
1,2,add-two-numbers,Add Two Numbers,5758,You are given two **non-empty** linked lists r...,{'c++': '```cpp struct ListNode { int val;...
2,3,longest-substring-without-repeating-characters,Longest Substring Without Repeating Characters,4422,"Given a string `s`, find the length of the **l...",{'c++': '```cpp #include <string> #include <un...
3,4,median-of-two-sorted-arrays,Median of Two Sorted Arrays,9908,Given two sorted arrays `nums1` and `nums2` of...,{'c++': '```cpp double findMedianSortedArrays(...
4,5,longest-palindromic-substring,Longest Palindromic Substring,3973,"Given a string `s`, return _the longest_ _pali...",{'c++': '```cpp #include <string> std::string...
...,...,...,...,...,...,...
2355,2608,shortest-cycle-in-a-graph,Shortest Cycle in a Graph,9585,There is a **bi-directional** graph with `n` v...,{'c++': '```cpp #include <vector> #include <qu...
2356,2609,find-the-longest-balanced-substring-of-a-binar...,Find the Longest Balanced Substring of a Binar...,1097,You are given a binary string `s` consisting o...,{'c++': '```cpp int longestBalancedSubstring(s...
2357,2610,convert-an-array-into-a-2d-array-with-conditions,Convert an Array Into a 2D Array With Conditions,4018,You are given an integer array `nums`. You nee...,{'c++': '```cpp #include <vector> #include <un...
2358,2611,mice-and-cheese,Mice and Cheese,4930,There are two mice and `n` different types of ...,{'c++': '```cpp #include <vector> #include <al...
2359,2612,minimum-reverse-operations,Minimum Reverse Operations,8715,You are given an integer `n` and an integer `p...,{'c++': '```cpp #include <vector> #include <se...

In [6]:
df = df[['title', 'difficulty', 'content']]

In [7]:
df

,title,difficulty,content
0,Two Sum,2812,Given an array of integers `nums` and an integ...
1,Add Two Numbers,5758,You are given two **non-empty** linked lists r...
2,Longest Substring Without Repeating Characters,4422,"Given a string `s`, find the length of the **l..."
3,Median of Two Sorted Arrays,9908,Given two sorted arrays `nums1` and `nums2` of...
4,Longest Palindromic Substring,3973,"Given a string `s`, return _the longest_ _pali..."
...,...,...,...
2355,Shortest Cycle in a Graph,9585,There is a **bi-directional** graph with `n` v...
2356,Find the Longest Balanced Substring of a Binar...,1097,You are given a binary string `s` consisting o...
2357,Convert an Array Into a 2D Array With Conditions,4018,You are given an integer array `nums`. You nee...
2358,Mice and Cheese,4930,There are two mice and `n` different types of ...
2359,Minimum Reverse Operations,8715,You are given an integer `n` and an integer `p...

In [8]:
df.iloc[0]['content']

'Given an array of integers `nums` and an integer `target`, return _indices of the two numbers such that they add up to `target`_.\n\nYou may assume that each input would have **_exactly_ one solution**, and you may not use the _same_ element twice.\n\nYou can return the answer in any order.\n\n**Example 1:**\n\n**Input:** nums = \\[2,7,11,15\\], target = 9\n**Output:** \\[0,1\\]\n**Explanation:** Because nums\\[0\\] + nums\\[1\\] == 9, we return \\[0, 1\\].\n\n**Example 2:**\n\n**Input:** nums = \\[3,2,4\\], target = 6\n**Output:** \\[1,2\\]\n\n**Example 3:**\n\n**Input:** nums = \\[3,3\\], target = 6\n**Output:** \\[0,1\\]\n\n**Constraints:**\n\n*   `2 <= nums.length <= 104`\n*   `-109 <= nums[i] <= 109`\n*   `-109 <= target <= 109`\n*   **Only one valid answer exists.**\n\n**Follow-up:** Can you come up with an algorithm that is less than `O(n2)` time complexity?'

In [29]:
# Extract description, examples, and constraints from content
import re

def extract_content_parts(content):
    # Extract description (everything before the first "**Example")
    description_match = re.search(r'^(.*?)(?=\*\*Example|\*\*Constraints:)', content, re.DOTALL)
    description = description_match.group(1).strip() if description_match else ""
    
    # Extract examples (from "**Example" to "**Constraints:")
    examples_section = re.search(r'(\*\*Example.*?)(?=\*\*Constraints:)', content, re.DOTALL)
    examples_text = examples_section.group(1) if examples_section else ""
    
    # Format examples to extract only Input and Output
    formatted_examples = []
    if examples_text:
        # Find all Input/Output pairs
        input_output_pairs = re.findall(r'\*\*Input:\*\*(.*?)\*\*Output:\*\*(.*?)(?=\*\*|$)', examples_text, re.DOTALL)
        
        for input_val, output_val in input_output_pairs:
            # Clean up the input and output values
            input_clean = re.sub(r'\s+', ' ', input_val.strip())
            output_clean = re.sub(r'\s+', ' ', output_val.strip())
            
            # Remove explanation parts (everything after "**Explanation:")
            # output_clean = re.sub(r'\*\*Explanation:.*', '', output_clean).strip()
            
            formatted_examples.append(f"Input: {input_clean}\n\nOutput: {output_clean}")
    
    examples = '\n\n'.join(formatted_examples)
    
    # Extract constraints (from "**Constraints:" to the end)
    constraints_match = re.search(r'\*\*Constraints:\*\*(.*)', content, re.DOTALL)
    constraints = constraints_match.group(1).strip() if constraints_match else ""
    
    # Remove backticks from constraints
    constraints = re.sub(r'`([^`]*)`', r'\1', constraints)
    
    # Remove asterisks (*) from constraints
    constraints = re.sub(r'\*', '', constraints)
    # Remove extra spaces but keep newlines
    constraints = re.sub(r'[ \t]+', ' ', constraints).strip()
    return description, examples, constraints

# Apply the extraction function to create new columns
df[['description', 'examples', 'constraints']] = df['content'].apply(
    lambda x: pd.Series(extract_content_parts(x))
)

In [30]:
# Display the extracted parts for verification
print("Description:")
print(df.iloc[0]['description'])
print("\n" + "="*50 + "\n")

print("Examples:")
print(df.iloc[0]['examples'])
print("\n" + "="*50 + "\n")

print("Constraints:")
print(df.iloc[0]['constraints'])

Description:
Given an array of integers `nums` and an integer `target`, return _indices of the two numbers such that they add up to `target`_.

You may assume that each input would have **_exactly_ one solution**, and you may not use the _same_ element twice.

You can return the answer in any order.

==================================================

Examples:
Input: nums = \[2,7,11,15\], target = 9

Output: \[0,1\]

Input: nums = \[3,2,4\], target = 6

Output: \[1,2\]

Input: nums = \[3,3\], target = 6

Output: \[0,1\]

==================================================

Constraints:
2 <= nums.length <= 104
 -109 <= nums[i] <= 109
 -109 <= target <= 109
 Only one valid answer exists.

Follow-up: Can you come up with an algorithm that is less than O(n2) time complexity?

In [31]:
# Check the final dataframe structure
df.head()

,title,difficulty,content,constraints,examples,description
0,Two Sum,2812,Given an array of integers `nums` and an integ...,2 <= nums.length <= 104\n -109 <= nums[i] <= 1...,"Input: nums = \[2,7,11,15\], target = 9\n\nOut...",Given an array of integers `nums` and an integ...
1,Add Two Numbers,5758,You are given two **non-empty** linked lists r...,The number of nodes in each linked list is in ...,"Input: l1 = \[2,4,3\], l2 = \[5,6,4\]\n\nOutpu...",You are given two **non-empty** linked lists r...
2,Longest Substring Without Repeating Characters,4422,"Given a string `s`, find the length of the **l...",0 <= s.length <= 5 104\n s consists of English...,"Input: s = ""abcabcbb ""\n\nOutput: 3\n\nInput: ...","Given a string `s`, find the length of the **l..."
3,Median of Two Sorted Arrays,9908,Given two sorted arrays `nums1` and `nums2` of...,nums1.length == m\n nums2.length == n\n 0 <= m...,"Input: nums1 = \[1,3\], nums2 = \[2\]\n\nOutpu...",Given two sorted arrays `nums1` and `nums2` of...
4,Longest Palindromic Substring,3973,"Given a string `s`, return _the longest_ _pali...",1 <= s.length <= 1000\n s consist of only digi...,"Input: s = ""babad ""\n\nOutput: ""bab ""\n\nInput...","Given a string `s`, return _the longest_ _pali..."

In [32]:
# Select only the relevant columns for the final dataset
final_df = df[['title', 'difficulty', 'description', 'examples', 'constraints']]
print("Final DataFrame shape:", final_df.shape)
print("\nColumns:", final_df.columns.tolist())
final_df.head()

Final DataFrame shape: (2360, 5)

Columns: ['title', 'difficulty', 'description', 'examples', 'constraints']

,title,difficulty,description,examples,constraints
0,Two Sum,2812,Given an array of integers `nums` and an integ...,"Input: nums = \[2,7,11,15\], target = 9\n\nOut...",2 <= nums.length <= 104\n -109 <= nums[i] <= 1...
1,Add Two Numbers,5758,You are given two **non-empty** linked lists r...,"Input: l1 = \[2,4,3\], l2 = \[5,6,4\]\n\nOutpu...",The number of nodes in each linked list is in ...
2,Longest Substring Without Repeating Characters,4422,"Given a string `s`, find the length of the **l...","Input: s = ""abcabcbb ""\n\nOutput: 3\n\nInput: ...",0 <= s.length <= 5 104\n s consists of English...
3,Median of Two Sorted Arrays,9908,Given two sorted arrays `nums1` and `nums2` of...,"Input: nums1 = \[1,3\], nums2 = \[2\]\n\nOutpu...",nums1.length == m\n nums2.length == n\n 0 <= m...
4,Longest Palindromic Substring,3973,"Given a string `s`, return _the longest_ _pali...","Input: s = ""babad ""\n\nOutput: ""bab ""\n\nInput...",1 <= s.length <= 1000\n s consist of only digi...

In [33]:
# Optional: Save the processed data to a new file
final_df.to_json('processed_leetcode_data.jsonl', orient='records', lines=True)
print("Data saved to 'processed_leetcode_data.jsonl'")

Data saved to 'processed_leetcode_data.jsonl'

In [ ]:
# store the processed data into postgresql
# convert 
from sqlalchemy import create_engine
engine = create_engine('postgresql://username:password@localhost:5432/mydatabase')
final_df.to_sql('leetcode_problems', engine, if_exists='replace', index=False)